version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports:
      - "27017:27017"